
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]

name = "vejde-rddl"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["gymnasium>=1.1.1", "pyrddlgym>=2.2", "rddlrepository>=2.0"]

[project.optional-dependencies]
cpu = ["regawa[cpu, rl]"]
cu128 = ["regawa[cu128, rl]"]


[tool.uv.sources]
regawa = { git = "git+ssh://git@gitr.sys.kth.se/jaknyb/RDDLGraphWrapper"}


[dependency-groups]
dev = ["pytest>=8.3.5", "matplotlib>=3.10.1", "graphviz>=0.20.3"]



[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu128" },
  ],
  [
    { package = "regawa", extra = "cpu" },
    { package = "regawa", extra = "cu128" },
  ],
  [
    { package = "regawa", extra = "cu128" },
    { package = "regawa", extra = "cpu" },
  ],
]
find-links = [
  "https://data.pyg.org/whl/torch-2.8.0+cu128.html",
  "https://data.pyg.org/whl/torch-2.8.0+cpu.html",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    "RUF",
    "PL",
    "PERF",
    "FLY",
    "W",
    #"FBT",
    "A",
    "Q",
    "RET",
    "ARG",
    "NPY",
    "FURB",
    #"TRY",
    #"C90",
]
ignore = ["B019", "E501", "RUF003", "PLR0913", "PLR0915"]
