
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]

name = "vejde-rddl"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["gymnasium>=1.1.1", "pyrddlgym>=2.2", "rddlrepository>=2.0"]

[project.optional-dependencies]
cpu = ["regawa[cpu]"]
cu124 = ["regawa[cu124]"]


[tool.uv.sources]
regawa = { git = "git+ssh://git@gitr.sys.kth.se/jaknyb/RDDLGraphWrapper", branch = "main" }


[dependency-groups]
dev = ["pytest>=8.3.5", "matplotlib>=3.10.1", "graphviz>=0.20.3"]


[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu124" },
  ],
  [
    { extra = "cpu" },
    { package = "regawa", extra = "cu124" },
  ],
  [
    { extra = "cu124" },
    { package = "regawa", extra = "cpu" },
  ],
]

find-links = [
  "https://data.pyg.org/whl/torch-2.5.0+cu124.html",
  "https://data.pyg.org/whl/torch-2.5.0+cpu.html",
]
